[window]
decorations = "none"
padding = { x = 25, y = 25 }
opacity = 0.5

[font]
size = 13.0

[colors]

[colors.primary]
background = "#800f2f"
foreground = "#ffc2d1"

[colors.cursor]
text = "#CCCCCC"
cursor = "#333333"

[colors.normal]
black   = "#1b263b"
red     = "#1b263b"
green   = "#1b263b"
yellow  = "#1b263b"
blue    = "#1b263b"
magenta = "#1b263b"
cyan    = "#1b263b"
white   = "#1b263b"

[colors.bright]
black   = "#4a4a4a"
red     = "#545454"
green   = "#5e5e5e"
yellow  = "#686868"
blue    = "#727272"
magenta = "#7c7c7c"
cyan    = "#868686"
white   = "#ffffff"

[colors.selection]
text = "#CCCCCC"
background = "#333333"

[colors.vi_mode_cursor]
text   = "#CCCCCC"
cursor = "#333333"
